# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.1

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/liaoyunyang/NTU_CSIE/2025_2/parallel_programming/final_project/parallel_team_work

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/liaoyunyang/NTU_CSIE/2025_2/parallel_programming/final_project/parallel_team_work

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/liaoyunyang/NTU_CSIE/2025_2/parallel_programming/final_project/parallel_team_work/CMakeFiles /Users/liaoyunyang/NTU_CSIE/2025_2/parallel_programming/final_project/parallel_team_work//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/liaoyunyang/NTU_CSIE/2025_2/parallel_programming/final_project/parallel_team_work/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named video_mosaic_common

# Build rule for target.
video_mosaic_common: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 video_mosaic_common
.PHONY : video_mosaic_common

# fast build rule for target.
video_mosaic_common/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/video_mosaic_common.dir/build.make CMakeFiles/video_mosaic_common.dir/build
.PHONY : video_mosaic_common/fast

#=============================================================================
# Target rules for targets named video_mosaic_cpu

# Build rule for target.
video_mosaic_cpu: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 video_mosaic_cpu
.PHONY : video_mosaic_cpu

# fast build rule for target.
video_mosaic_cpu/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/video_mosaic_cpu.dir/build.make CMakeFiles/video_mosaic_cpu.dir/build
.PHONY : video_mosaic_cpu/fast

#=============================================================================
# Target rules for targets named metal_shaders

# Build rule for target.
metal_shaders: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 metal_shaders
.PHONY : metal_shaders

# fast build rule for target.
metal_shaders/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/metal_shaders.dir/build.make CMakeFiles/metal_shaders.dir/build
.PHONY : metal_shaders/fast

#=============================================================================
# Target rules for targets named video_mosaic_metal

# Build rule for target.
video_mosaic_metal: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 video_mosaic_metal
.PHONY : video_mosaic_metal

# fast build rule for target.
video_mosaic_metal/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/video_mosaic_metal.dir/build.make CMakeFiles/video_mosaic_metal.dir/build
.PHONY : video_mosaic_metal/fast

src/apps/video_mosaic_cpu.o: src/apps/video_mosaic_cpu.cpp.o
.PHONY : src/apps/video_mosaic_cpu.o

# target to build an object file
src/apps/video_mosaic_cpu.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/video_mosaic_cpu.dir/build.make CMakeFiles/video_mosaic_cpu.dir/src/apps/video_mosaic_cpu.cpp.o
.PHONY : src/apps/video_mosaic_cpu.cpp.o

src/apps/video_mosaic_cpu.i: src/apps/video_mosaic_cpu.cpp.i
.PHONY : src/apps/video_mosaic_cpu.i

# target to preprocess a source file
src/apps/video_mosaic_cpu.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/video_mosaic_cpu.dir/build.make CMakeFiles/video_mosaic_cpu.dir/src/apps/video_mosaic_cpu.cpp.i
.PHONY : src/apps/video_mosaic_cpu.cpp.i

src/apps/video_mosaic_cpu.s: src/apps/video_mosaic_cpu.cpp.s
.PHONY : src/apps/video_mosaic_cpu.s

# target to generate assembly for a file
src/apps/video_mosaic_cpu.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/video_mosaic_cpu.dir/build.make CMakeFiles/video_mosaic_cpu.dir/src/apps/video_mosaic_cpu.cpp.s
.PHONY : src/apps/video_mosaic_cpu.cpp.s

src/apps/video_mosaic_metal.o: src/apps/video_mosaic_metal.cpp.o
.PHONY : src/apps/video_mosaic_metal.o

# target to build an object file
src/apps/video_mosaic_metal.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/video_mosaic_metal.dir/build.make CMakeFiles/video_mosaic_metal.dir/src/apps/video_mosaic_metal.cpp.o
.PHONY : src/apps/video_mosaic_metal.cpp.o

src/apps/video_mosaic_metal.i: src/apps/video_mosaic_metal.cpp.i
.PHONY : src/apps/video_mosaic_metal.i

# target to preprocess a source file
src/apps/video_mosaic_metal.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/video_mosaic_metal.dir/build.make CMakeFiles/video_mosaic_metal.dir/src/apps/video_mosaic_metal.cpp.i
.PHONY : src/apps/video_mosaic_metal.cpp.i

src/apps/video_mosaic_metal.s: src/apps/video_mosaic_metal.cpp.s
.PHONY : src/apps/video_mosaic_metal.s

# target to generate assembly for a file
src/apps/video_mosaic_metal.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/video_mosaic_metal.dir/build.make CMakeFiles/video_mosaic_metal.dir/src/apps/video_mosaic_metal.cpp.s
.PHONY : src/apps/video_mosaic_metal.cpp.s

src/common/TileDatabase.o: src/common/TileDatabase.cpp.o
.PHONY : src/common/TileDatabase.o

# target to build an object file
src/common/TileDatabase.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/video_mosaic_common.dir/build.make CMakeFiles/video_mosaic_common.dir/src/common/TileDatabase.cpp.o
.PHONY : src/common/TileDatabase.cpp.o

src/common/TileDatabase.i: src/common/TileDatabase.cpp.i
.PHONY : src/common/TileDatabase.i

# target to preprocess a source file
src/common/TileDatabase.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/video_mosaic_common.dir/build.make CMakeFiles/video_mosaic_common.dir/src/common/TileDatabase.cpp.i
.PHONY : src/common/TileDatabase.cpp.i

src/common/TileDatabase.s: src/common/TileDatabase.cpp.s
.PHONY : src/common/TileDatabase.s

# target to generate assembly for a file
src/common/TileDatabase.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/video_mosaic_common.dir/build.make CMakeFiles/video_mosaic_common.dir/src/common/TileDatabase.cpp.s
.PHONY : src/common/TileDatabase.cpp.s

src/common/VideoMosaicGenerator.o: src/common/VideoMosaicGenerator.cpp.o
.PHONY : src/common/VideoMosaicGenerator.o

# target to build an object file
src/common/VideoMosaicGenerator.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/video_mosaic_common.dir/build.make CMakeFiles/video_mosaic_common.dir/src/common/VideoMosaicGenerator.cpp.o
.PHONY : src/common/VideoMosaicGenerator.cpp.o

src/common/VideoMosaicGenerator.i: src/common/VideoMosaicGenerator.cpp.i
.PHONY : src/common/VideoMosaicGenerator.i

# target to preprocess a source file
src/common/VideoMosaicGenerator.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/video_mosaic_common.dir/build.make CMakeFiles/video_mosaic_common.dir/src/common/VideoMosaicGenerator.cpp.i
.PHONY : src/common/VideoMosaicGenerator.cpp.i

src/common/VideoMosaicGenerator.s: src/common/VideoMosaicGenerator.cpp.s
.PHONY : src/common/VideoMosaicGenerator.s

# target to generate assembly for a file
src/common/VideoMosaicGenerator.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/video_mosaic_common.dir/build.make CMakeFiles/video_mosaic_common.dir/src/common/VideoMosaicGenerator.cpp.s
.PHONY : src/common/VideoMosaicGenerator.cpp.s

src/gpu/metal_compute.o: src/gpu/metal_compute.mm.o
.PHONY : src/gpu/metal_compute.o

# target to build an object file
src/gpu/metal_compute.mm.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/video_mosaic_metal.dir/build.make CMakeFiles/video_mosaic_metal.dir/src/gpu/metal_compute.mm.o
.PHONY : src/gpu/metal_compute.mm.o

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... metal_shaders"
	@echo "... video_mosaic_common"
	@echo "... video_mosaic_cpu"
	@echo "... video_mosaic_metal"
	@echo "... src/apps/video_mosaic_cpu.o"
	@echo "... src/apps/video_mosaic_cpu.i"
	@echo "... src/apps/video_mosaic_cpu.s"
	@echo "... src/apps/video_mosaic_metal.o"
	@echo "... src/apps/video_mosaic_metal.i"
	@echo "... src/apps/video_mosaic_metal.s"
	@echo "... src/common/TileDatabase.o"
	@echo "... src/common/TileDatabase.i"
	@echo "... src/common/TileDatabase.s"
	@echo "... src/common/VideoMosaicGenerator.o"
	@echo "... src/common/VideoMosaicGenerator.i"
	@echo "... src/common/VideoMosaicGenerator.s"
	@echo "... src/gpu/metal_compute.o"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

